image: Visual Studio 2017

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

environment:
  Appveyor: true

init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

build_script:
  # Our stuff
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
  - path: .\.nupkgs\*.nupkg
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/kingensoft/api/v2
  on:
    branch: master  
  api_key:
    secure: zZwKxhP5rXO3+XzCfPm8fa+iHJVB1B54RGx3FQTVRPK8226VgtFQAejeQlh9Vvnb
  symbol_server: https://www.myget.org/F/kingensoft/symbols/api/v2/package